INSERT INTO ARTIST (NAME, COUNTRY, BIO) VALUES ('Adele', 'UK', 'Adele is the best-selling artist of XXI century, great voice, used to be fat but not anymore');
INSERT INTO ARTIST (NAME, COUNTRY, BIO) VALUES ('James Blake', 'UK', 'Really hot and experimental dude whos been a critics favourite for almost a decade ');
INSERT INTO ARTIST (NAME, COUNTRY, BIO) VALUES ('Kylie Minogue', 'OZ', 'Pop-icon with a career spanned for several decades ');
INSERT INTO ARTIST (NAME, COUNTRY, BIO) VALUES ('Fleetwood Mac', 'UK', 'British/American band that is known for multiple line-up changes and endless re-invention of their music genre');
INSERT INTO ARTIST (NAME, COUNTRY, BIO) VALUES ('Foxes', 'UK', 'Great synthpop star from the uK, not as famous as she had to be');

INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('30', 1, 2021, '30 is the fourth studio album by English singer-songwriter Adele, released on 19 November 2021 by Melted Stone and Columbia Records. As her return to music after a six-year hiatus since the release of her third studio album 25 (2015), 30 centres on Adele''s divorce, motherhood, fame, heartache, acceptance, and hope. The album reached number one in 24 territories, including the UK where it opened with the highest first-week sales for an album by a female artist since Adele''s own 25 and became the country''s best-selling album of the 2020s decade. In the US, it was Adele''s third consecutive Billboard 200 number-one album and the best-selling album of 2021. 30 was certified 3× Platinum by the Recording Industry Association of America (RIAA), marking Adele''s fourth multi-platinum album in the US.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('Friends That Break Your Heart', 2, 2021, 'Friends That Break Your Heart is the fifth studio album by English singer-songwriter and producer James Blake. It was released by Republic Records and Polydor Records on 8 October 2021, after initially being scheduled for release on 10 September 2021 before being postponed due to delays in physical production as a result of the COVID-19 pandemic.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('25', 1, 2015, '25 is the third studio album by English singer-songwriter Adele, released on 20 November 2015 by XL Recordings and Columbia Records. The album is titled as a reflection of her life and frame of mind at 25 years old and is termed a "make-up record". Its lyrical content features themes of Adele "yearning for her old self, her nostalgia", and "melancholia about the passage of time" according to an interview with the singer by Rolling Stone, as well as themes of motherhood and regret. In contrast to Adele''s previous works, the production of 25 incorporated the use of electronic elements and creative rhythmic patterns, with elements of 1980s R&B and organs.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('21', 1, 2011, '21 is the second studio album by English singer-songwriter Adele. It was released on 24 January 2011[1] in Europe by XL Recordings and on 22 February 2011 in North America by Columbia Records. The album was named after the age of the singer during its production. 21 shares the Motown/soul influences of her 2008 debut album 19, but also draws influence from the American country and Southern blues music that Adele started listening to during the North American leg of her tour An Evening with Adele. Composed in the aftermath of the singer''s separation from her then partner, the album exemplifies the near dormant tradition of the confessional singer-songwriter, exploring themes of heartbreak, healing, introspection, and forgiveness.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('Fever', 3, 2001, 'Fever is the eighth studio album by Australian singer Kylie Minogue. It was released on 1 October 2001 internationally by Parlophone and later launched in the United States on 26 February 2002 by Capitol Records. Minogue worked with writers and producers such as Cathy Dennis, Rob Davis, Richard Stannard, Julian Gallagher, TommyD, Tom Nichols, Pascal Gabriel and others to create a disco and Europop-influenced dance-pop album. Other musical influences of the album range from synth-pop to club music. Upon its release, Fever received positive reviews from music critics, many of whom praised its production and commercial appeal. The album was a commercial success, peaking at number one in Australia, Austria, Germany, Ireland, and the UK. ');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('Golden', 3, 2018, 'Golden is the fourteenth studio album by Australian singer Kylie Minogue, released on 6 April 2018 by Darenote and BMG Rights Management. The album was co-produced by Minogue alongside a variety of producers including Ash Howes, Richard "Biff" Stannard, Sky Adams, Alex Smith, and Mark Taylor, among others. Each track was co-written by Minogue, making it her first album since Impossible Princess (1997) in which this was the case. A large portion of the record was recorded in Nashville, Tennessee, where she found new inspiration with its music, and also recorded some material in London and Los Angeles.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('DISCO', 3, 2020, 'Disco is the fifteenth studio album by Australian singer Kylie Minogue. It was released on 6 November 2020 by Darenote and BMG Rights Management. Following the completion of the Golden Tour and her performance at the Glastonbury Festival in 2019, Minogue sought to create a disco-influenced record and enlisted producers such as Sky Adams, Teemu Brunila and Biff Stannard. Minogue herself also gained engineering credits for vocals and synths. Disco received positive reviews from music critics, many of whom praised its fusion of retro and modern production and cohesiveness.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('Rumours', 4, 1977, 'Rumours is the eleventh studio album by British-American rock band Fleetwood Mac, released on 4 February 1977 by Warner Bros. Records. Largely recorded in California in 1976, it was produced by the band with Ken Caillat and Richard Dashut. The band wanted to expand on the commercial success of their self-titled 1975 album. The group recorded the album in the aftermath of relationship breakups among its members and heavy drug use, both of which shaped the album''s lyrics.');
INSERT INTO ALBUM (TITLE, ARTIST_ID, YEAR, INFO) VALUES('Tusk', 4, 1979, '');

INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (1, '2021-11-19', 'CD', null, 'Columbia', 550, 'https://upload.wikimedia.org/wikipedia/ru/7/76/Adele_-_30.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (1, '2021-11-19', 'LP', 'White', 'Columbia', 2500, 'https://upload.wikimedia.org/wikipedia/ru/7/76/Adele_-_30.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (1, '2021-11-19', 'LP', 'Black', 'Columbia', 2300, 'https://upload.wikimedia.org/wikipedia/ru/7/76/Adele_-_30.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (1, '2021-11-19', 'LP', 'Clear', 'Columbia', 2500, 'https://upload.wikimedia.org/wikipedia/ru/7/76/Adele_-_30.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (2, '2021-10-08', 'CD', null, 'Republic', 900, 'https://upload.wikimedia.org/wikipedia/en/f/f9/Friends_That_Break_Your_Heart.jpg');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (2, '2021-10-08', 'LP', 'Alt Cover', 'Republic', 2300, 'https://cdn1.ozone.ru/s3/multimedia-q/6153430298.jpg');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (3, '2021-10-08', 'LP', null, 'Columbia', 2300, 'https://showbi.ru/_data/i/upload/2015/10/23/20151023103920-f7f80671-me.jpg');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (4, '2011-01-24', 'LP', null, 'Columbia', 2300, 'https://upload.wikimedia.org/wikipedia/en/1/1b/Adele_-_21.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (5, '2021-11-21', 'LP', 'White', 'Parlophone', 2600, 'https://upload.wikimedia.org/wikipedia/en/a/a9/Kylie_Minogue_-_Fever.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (5, '2021-10-14', 'LP', 'Silver', 'Parlophone', 2400, 'https://upload.wikimedia.org/wikipedia/en/a/a9/Kylie_Minogue_-_Fever.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (6, '2018-04-14', 'LP', 'Clear', 'BMG', 2100, 'https://upload.wikimedia.org/wikipedia/en/e/e5/Kylie_Minogue_-_Golden.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (7, '2020-11-06', 'LP', null, 'BMG', 2500, 'https://upload.wikimedia.org/wikipedia/en/6/6a/Kylie_Minogue_-_Disco.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (7, '2020-10-14', 'CD', null, 'BMG', 600, 'https://upload.wikimedia.org/wikipedia/en/6/6a/Kylie_Minogue_-_Disco.png');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (7, '2021-11-12', 'LP', 'Guest List Edition', 'BMG', 4200, 'https://upload.wikimedia.org/wikipedia/en/5/59/Disco_guest_list.jpeg');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (8, '2012-01-06', 'LP', null, 'Warner', 1800, 'https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (8, '2015-01-07', 'LP', null, 'Warner', 3800, 'https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG');
INSERT INTO RELEASE (ALBUM_ID, RELEASE_DATE, FORMAT, NOTES, LABEL, PRICE, IMG) VALUES (8, '2019-01-06', 'LP', 'Clear', 'Warner', 4500, 'https://upload.wikimedia.org/wikipedia/en/f/fb/FMacRumours.PNG');


INSERT INTO USERS (username, password, enabled) values ('user', '{bcrypt}$2y$10$fpZPXdN9fSCiGio4AwAIW.ZBEZ4nVz9nI/wM7bT5/CDZAjcixCfWO', true);
INSERT INTO USERS (username, password, enabled) values ('admin', '{bcrypt}$2y$10$/n5HsyiwBkwU3WeJNSqrJO1zWMRO1cTOn9wkUytUvS64SKvf.MxHe', true);

INSERT INTO AUTHORITIES (username, authority) values ('user', 'ROLE_USER');
INSERT INTO AUTHORITIES (username, authority) values ('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES (username, authority) values ('admin', 'ROLE_ADMIN');